hosts: [
  { host_ip: "192.168.57.160", host_name: "k8s-m1"},
  { host_ip: "192.168.57.161", host_name: "k8s-n1"},
  { host_ip: "192.168.57.162", host_name: "k8s-n2"}  
]
parameters: [
  { name: "vm.max_map_count", value: "262144"},
  { name: "vm.overcommit_memory", value: "1"},
  { name: "vm.swappiness", value: "0"},
  { name: "net.core.somaxconn", value: "65535"},
  { name: "net.ipv4.tcp_max_syn_backlog", value: "65535"}
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" }
  ]
