---

- hosts: kube-cluster
  gather_facts: yes
  remote_user: vagrant
  serial: 1
  become: yes
  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }

- hosts: master
  gather_facts: yes
  remote_user: vagrant
  serial: 1 
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }

- hosts: node
  gather_facts: yes
  remote_user: vagrant
  serial: 1
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }
